replace pass word credentials with  gh key file

diff --git a/git-mirror b/git-mirror
--- a/git-mirror
+++ b/git-mirror
@@ -17,7 +17,7 @@ function show_usage() {
 	echo mirror repo to git hub
 	echo 'example usage: git_mirror.sh abc bzr http://launchpad/abc "" --debug --dry-run
 	--fast skip svn cvs
-	--interactive require user input
+	--interactive|-i require user input
 	--quiet no progress info
 	--resume experiment to resume existing svn cvs mirror
 	--small less 100 meg
@@ -155,35 +155,50 @@ msg(){
 	fi
 }
 
+api_request() {
+	api="curl -s https://api.github.com/"
+	json=$($api$1)
+	error=$(echo $json | jshon -Q -e message -u)
+	if [[ "$error" = "API rate limit exceeded"* ]]; then
+		# if [[ -n "$error" ]]; then
+		# if true; then
+		echo error $error;
+		echo API unavailable
+		error=true
+	else
+		error=false
+	fi
+}
+
 # cloud machine are rate limited
 function have_api() {
 	if $isdry && ! $istest; then
 		haveapi=false
 		return
 	fi
-	json=$(curl -s https://api.github.com/repos/$org/$to)
-	error=$(echo $json | jshon -Q -e message -u)
-	if [[ "$error" = "API rate limit exceeded"* ]]; then
-		# if [[ -n "$error" ]]; then
-		# if true; then
-		# echo error $error;
-		if [ -z "$user" ]; then
-			echo user unset API unavailable
-		else
-			# retry with credentials
-			# json=$(curl -s -u "$user:$pwd" https://api.github.com/repos/$org/$to)
-			json=$(gh api repos/$org/$to)
-			error=$(echo $json | jshon -Q -e message -u)
-			if [ -z "$error" ]; then
-				haveapi=true
-				login="-u $user:$pwd"
-			else
-				# echo error $error
-				echo API unavailable
-			fi
-		fi
+
+	api_request repos/$org/$to
+	if $error; then
+		haveapi=false
 	else
 		haveapi=true
+		api="curl -s https://api.github.com/"
+	fi
+		
+	# don't risk bot label because of this
+	if false; then
+	# if [ -z "$user" ]; then
+		# echo user unset API unavailable
+	# else
+		# retry with credentials
+		# json=$(curl -s -u "$user:$pwd" https://api.github.com/repos/$org/$to)
+		json=$(gh api repos/$org/$to)
+		error=$(echo $json | jshon -Q -e message -u)
+		if [ -z "$error" ]; then
+			haveapi=true
+			# login="-u $user:$pwd"
+			api="gh api "
+		fi
 	fi
 }
 
@@ -192,12 +207,13 @@ function is_big() {
 	echo checking size
 	if $isdry && ! $istest; then	return 0; fi
 	if ! $haveapi; then	return 0; fi
-	json=$(curl -s $login https://api.github.com/repos/$org/$to)
+	# json=$(curl -s $login https://api.github.com/repos/$org/$to)
+	json=$(${api}repos/$org/$to)
 	size=$(echo $json|jshon -e size -u)
 	megs=$(numfmt --to=iec $(($size*1024)))
 	if [ $size -gt 100000 ]; then
 		format false 9 $megs too big for --fast and --small
-		exit 1
+		exit 0
 	else
 		format false 2 $megs
 	fi
@@ -207,10 +223,15 @@ function is_big() {
 function is_behind() {
 	if ! $haveapi; then	return 0; fi
 	echo comparing head dates
-	if  $isdry && ! $istest; then	return 0; fi
+	if $isdry && ! $istest; then	return 0; fi
 
 	# json=$(curl -s $login https://api.github.com/repos/$org/$to/branches/master)
-	json=$(gh api repos/$org/$to/branches/master)
+	# json=$(gh api repos/$org/$to/branches/master)
+	api_request repos/$org/$to/branches/master
+	if $error; then
+		echo unable to read mirror  head date
+		exit
+	fi
 	md=$(echo $json|jq -r '.. | .date? | strings'|tail -1)
 
 	case "$type" in
@@ -224,39 +245,41 @@ function is_behind() {
 			sd=$(date -u -Is -d "$(cvs -d $from history -a -T|tail -1|cut -f2-4 -d" ")" |sed s,+00:00,Z,)
 			# cvs -d $from log -N| grep ^date: | sort | tail -n 1 | cut -d\; -f1
 			;;
+
 		svn)
 			sd=$(date -u -Is -d "$(svn info $from| grep 'Date' |cut -d' ' -f4-6)"|sed s,+00:00,Z,)
 			;;
+
 		git|hg)
 
 			if $istest ; then
-				echo last commit $md
+				echo last mirror commit $md
 				return 0
 			fi
 
-	# shopt -u expand_aliases
-	rm -rf tmp
-	mkdir tmp
-	pushd tmp
-	echo cloning $from ...
-	git $c $from .
-	sd=$(TZ=UTC0 git show HEAD --quiet --date=iso-strict-local --format="%cd"|sed "s,+00:00,Z,")
-	popd
-	# shopt -s expand_aliases
-	;;
+			# shopt -u expand_aliases
+			rm -rf tmp
+			mkdir tmp
+			pushd tmp
+			echo reading remote head date ...
+			git $c $from .
+			sd=$(TZ=UTC0 git show HEAD --quiet --date=iso-strict-local --format="%cd"|sed "s,+00:00,Z,")
+			popd
+			# shopt -s expand_aliases
+			;;
 
-*)
-	format false 10 mirror date $md
-	format false 9 add $type date comparison
-	return 0;;
-esac
+		*)
+			format false 10 mirror date $md
+			format false 9 add $type date comparison
+			return 0;;
+	esac
 
-if [ "$sd" == "$md" ]; then
-	format false 2 up to date $sd
-	exit 0
-else
-	format false 9 updating from $md to $sd
-fi
+	if [ "$sd" == "$md" ]; then
+		format false 2 up to date $sd
+		exit 0
+	else
+		format false 9 updating from $md to $sd
+	fi
 }
 
 function remote_exist() {
@@ -270,10 +293,12 @@ function remote_exist() {
 		cvs|svn)
 			if [ $? -ne 0 ]; then
 				exit 1
-				fi;;
-			*)
-				return 0
-		esac
+			fi
+			;;
+		*)
+			return 0
+			;;
+	esac
 }
 
 function mirror_exist() {
@@ -305,7 +330,8 @@ function create_repo() {
 	if $isdry; then	return 0; fi
 
 	# create repo
-	json=$(curl -s -u $user:$pwd -d "{\"name\":\"$to\"}" https://api.github.com/orgs/$org/repos)
+	# json=$(curl -s -u $user:$pwd -d "{\"name\":\"$to\"}" https://api.github.com/orgs/$org/repos)
+	json=$(gh -f name=$name orgs/$org/repos)
 	error=$(echo "$json" | jshon -Q -e message -u)
 	if [ -n "$error" ]; then
 		echo $error;
@@ -319,7 +345,7 @@ function create_repo() {
 # repo home
 : ${REPO_HOME=~/repos}
 if ! $dryrun && [ ! -d "$REPO_HOME" ]; then
-	read -n1 -p "create repo home $REPO_HOME? [y/↵]/* " yn
+	read -n1 -p "create repo home $REPO_HOME? [y/*] " yn
 	if test $yn = y; then
 		mkdir $REPO_HOME
 	fi
@@ -412,6 +438,7 @@ remote_exist
 if $isint; then
 	read -s -n 1 -p "mirror $name [␣↵ / * / q]" yn
 	echo
+	# echo yn=$yn
 	case $yn in
 		"" ) ;;
 		"q" ) exit 9;;
@@ -421,27 +448,6 @@ if $isint; then
 			;;
 	esac
 fi
-
-resume_repo(){
-	echo clone existing mirror
-	git clone --mirror git@github.com:$org/$to .
-
-	echo post processing
-	case "$type" in
-		bzr)
-			git branch master;;
-	esac
-	case "$name" in
-		jdownloader)
-			java -jar bfg.jar --strip-blobs-bigger-than 50M
-			if [ $? -ne 0 ]; then exit $?; fi
-			;;
-	esac
-
-	echo update remote
-	git remote $s origin $from
-	git remote $r origin git@github.com:$org/$to
-}
 
 new_repo(){
 	msg no existing clone on disk
@@ -458,7 +464,9 @@ new_repo(){
 
 	# api
 	haveapi=false
-	have_api
+	haveapi=true
+	# this test will drain request quota
+	# have_api
 
 	# test
 	if $istest; then
@@ -469,8 +477,9 @@ new_repo(){
 		# exit
 	fi
 
+	# careful with rate limit and bot label 
 	is_big
-
+	# compare head dates
 	is_behind
 
 	echo creating new folder $to
@@ -486,14 +495,32 @@ new_repo(){
 	# this produce errors related to pull requests refs/pull/1/head
 	# if $isresume && $isgit; then
 	if false; then
-		resume_repo
+		echo clone existing mirror
+		git clone --mirror git@github.com:$org/$to .
 	else
 		msg $(date -Im -u)Z cloning $from ...
 		export GIT_SSL_NO_VERIFY=1
 		# git config --global http.sslVerify false
 		git $c
+
+		echo post processing
+
+		# case "$type" in
+		# 	bzr)
+		# 		git branch master;;
+		# esac
+
+		case "$name" in
+			jdownloader)
+				java -jar bfg.jar --strip-blobs-bigger-than 50M
+				if [ $? -ne 0 ]; then exit $?; fi
+				;;
+		esac
+
 		echo update remote address
 		git remote $r origin git@github.com:$org/$to
+		# git remote $s origin $from
+		# git remote $r origin git@github.com:$org/$to
 	fi
 }
 
